# Generated by Django 4.2.7 on 2025-08-08 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InformacionAlbergue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(default="Protectora Adán", max_length=200)),
                ("mision", models.TextField()),
                ("vision", models.TextField()),
                ("historia", models.TextField()),
                ("direccion", models.TextField()),
                ("telefono", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("horarios", models.TextField()),
                ("facebook_url", models.URLField(blank=True)),
                ("instagram_url", models.URLField(blank=True)),
                ("twitter_url", models.URLField(blank=True)),
                ("whatsapp", models.CharField(blank=True, max_length=20)),
                (
                    "numero_cuenta",
                    models.CharField(
                        blank=True,
                        help_text="Número de cuenta para donaciones",
                        max_length=50,
                    ),
                ),
                ("capacidad_perros", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Información del albergue",
                "verbose_name_plural": "Información del albergue",
            },
        ),
        migrations.CreateModel(
            name="Testimonio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("contenido", models.TextField()),
                ("perro_adoptado", models.CharField(blank=True, max_length=100)),
                (
                    "imagen",
                    models.ImageField(blank=True, null=True, upload_to="testimonios/"),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("mostrar", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Testimonio",
                "verbose_name_plural": "Testimonios",
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="Voluntario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("apellidos", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("telefono", models.CharField(max_length=20)),
                ("direccion", models.TextField()),
                ("fecha_nacimiento", models.DateField()),
                ("experiencia", models.TextField()),
                ("disponibilidad", models.TextField()),
                ("motivacion", models.TextField()),
                ("fecha_solicitud", models.DateTimeField(auto_now_add=True)),
                ("aprobado", models.BooleanField(default=False)),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Voluntario",
                "verbose_name_plural": "Voluntarios",
                "ordering": ["-fecha_solicitud"],
            },
        ),
    ]
