# Generated by Django 4.2.7 on 2025-08-08 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Aviso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("contenido", models.TextField()),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("urgente", "Urgente"),
                            ("importante", "Importante"),
                            ("informativo", "Informativo"),
                            ("evento", "Evento"),
                        ],
                        default="informativo",
                        max_length=15,
                    ),
                ),
                (
                    "imagen",
                    models.ImageField(blank=True, null=True, upload_to="avisos/"),
                ),
                ("activo", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_vencimiento", models.DateTimeField(blank=True, null=True)),
                ("destacado", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Aviso",
                "verbose_name_plural": "Avisos",
                "ordering": ["-fecha_creacion"],
            },
        ),
        migrations.CreateModel(
            name="TipoDonacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField()),
                (
                    "precio_sugerido",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "imagen",
                    models.ImageField(blank=True, null=True, upload_to="donaciones/"),
                ),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Tipo de donación",
                "verbose_name_plural": "Tipos de donaciones",
            },
        ),
        migrations.CreateModel(
            name="Donacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_donante", models.CharField(max_length=100)),
                ("email_donante", models.EmailField(max_length=254)),
                ("telefono_donante", models.CharField(blank=True, max_length=20)),
                ("cantidad", models.DecimalField(decimal_places=2, max_digits=10)),
                ("mensaje", models.TextField(blank=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("procesando", "Procesando"),
                            ("completada", "Completada"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="pendiente",
                        max_length=15,
                    ),
                ),
                ("fecha_donacion", models.DateTimeField(auto_now_add=True)),
                ("anonimo", models.BooleanField(default=False)),
                (
                    "tipo_donacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="donaciones.tipodonacion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Donación",
                "verbose_name_plural": "Donaciones",
                "ordering": ["-fecha_donacion"],
            },
        ),
    ]
