# Generated by Django 4.2.7 on 2025-08-08 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donaciones", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="donacion",
            name="authorization_code",
            field=models.CharField(
                blank=True, help_text="Código de autorización", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="donacion",
            name="buy_order",
            field=models.CharField(
                blank=True, help_text="Orden de compra", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="donacion",
            name="session_id",
            field=models.CharField(
                blank=True, help_text="ID de sesión", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="donacion",
            name="token_ws",
            field=models.CharField(
                blank=True, help_text="Token de WebPay", max_length=200, null=True
            ),
        ),
        migrations.AddField(
            model_name="donacion",
            name="transaction_date",
            field=models.DateTimeField(
                blank=True, help_text="Fecha de transacción WebPay", null=True
            ),
        ),
        migrations.AddField(
            model_name="donacion",
            name="webpay_response",
            field=models.JSONField(
                blank=True, help_text="Respuesta completa de WebPay", null=True
            ),
        ),
        migrations.AlterField(
            model_name="donacion",
            name="estado",
            field=models.CharField(
                choices=[
                    ("pendiente", "Pendiente"),
                    ("procesando", "Procesando"),
                    ("completada", "Completada"),
                    ("cancelada", "Cancelada"),
                    ("rechazada", "Rechazada"),
                ],
                default="pendiente",
                max_length=15,
            ),
        ),
    ]
