# Generated by Django 5.2 on 2025-08-10 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donaciones", "0002_donacion_authorization_code_donacion_buy_order_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donacion",
            name="estado",
            field=models.CharField(
                choices=[
                    ("pendiente", "Pendiente"),
                    ("procesando", "Procesando"),
                    ("completada", "Completada"),
                    ("cancelada", "Cancelada"),
                    ("rechazada", "Rechazada"),
                    ("fallida", "Fallida"),
                ],
                default="pendiente",
                max_length=15,
            ),
        ),
    ]
