# Generated by Django 4.2.7 on 2025-08-08 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FiltroAdopcion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(max_length=40)),
                (
                    "tamano",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pequeño", "Pequeño"),
                            ("mediano", "Mediano"),
                            ("grande", "Grande"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "sexo",
                    models.CharField(
                        blank=True,
                        choices=[("macho", "Macho"), ("hembra", "Hembra")],
                        max_length=10,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("negro", "Negro"),
                            ("blanco", "Blanco"),
                            ("marron", "Marrón"),
                            ("dorado", "Dorado"),
                            ("gris", "Gris"),
                            ("mixto", "Mixto"),
                        ],
                        max_length=10,
                    ),
                ),
                ("edad_min", models.PositiveIntegerField(blank=True, null=True)),
                ("edad_max", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Filtro de adopción",
                "verbose_name_plural": "Filtros de adopción",
            },
        ),
        migrations.CreateModel(
            name="Perro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("edad", models.PositiveIntegerField(help_text="Edad en años")),
                (
                    "tamano",
                    models.CharField(
                        choices=[
                            ("pequeño", "Pequeño"),
                            ("mediano", "Mediano"),
                            ("grande", "Grande"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "sexo",
                    models.CharField(
                        choices=[("macho", "Macho"), ("hembra", "Hembra")],
                        max_length=10,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("negro", "Negro"),
                            ("blanco", "Blanco"),
                            ("marron", "Marrón"),
                            ("dorado", "Dorado"),
                            ("gris", "Gris"),
                            ("mixto", "Mixto"),
                        ],
                        max_length=10,
                    ),
                ),
                ("raza", models.CharField(blank=True, max_length=100)),
                ("descripcion", models.TextField()),
                (
                    "imagen",
                    models.ImageField(blank=True, null=True, upload_to="perros/"),
                ),
                ("vacunado", models.BooleanField(default=False)),
                ("esterilizado", models.BooleanField(default=False)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("disponible", "Disponible"),
                            ("en_proceso", "En proceso de adopción"),
                            ("adoptado", "Adoptado"),
                        ],
                        default="disponible",
                        max_length=15,
                    ),
                ),
                ("fecha_ingreso", models.DateField(auto_now_add=True)),
                (
                    "peso",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Peso en kg",
                        max_digits=5,
                        null=True,
                    ),
                ),
                ("bueno_con_niños", models.BooleanField(default=True)),
                ("bueno_con_otros_perros", models.BooleanField(default=True)),
                (
                    "necesidades_especiales",
                    models.TextField(
                        blank=True, help_text="Descripción de necesidades especiales"
                    ),
                ),
            ],
            options={
                "verbose_name": "Perro",
                "verbose_name_plural": "Perros",
                "ordering": ["-fecha_ingreso"],
            },
        ),
        migrations.CreateModel(
            name="SolicitudAdopcion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_solicitante", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("telefono", models.CharField(max_length=20)),
                ("direccion", models.TextField()),
                ("experiencia_mascotas", models.TextField()),
                ("motivo_adopcion", models.TextField()),
                ("vivienda_tipo", models.CharField(max_length=100)),
                ("patio", models.BooleanField(default=False)),
                ("otros_animales", models.TextField(blank=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("en_revision", "En revisión"),
                            ("aprobada", "Aprobada"),
                            ("rechazada", "Rechazada"),
                        ],
                        default="pendiente",
                        max_length=15,
                    ),
                ),
                ("fecha_solicitud", models.DateTimeField(auto_now_add=True)),
                ("notas_admin", models.TextField(blank=True)),
                (
                    "perro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="adopciones.perro",
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitud de adopción",
                "verbose_name_plural": "Solicitudes de adopción",
                "ordering": ["-fecha_solicitud"],
            },
        ),
    ]
