# Generated by Django 5.2 on 2025-08-10 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adopciones", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="solicitudadopcion",
            name="otros_animales",
            field=models.TextField(
                blank=True, help_text="Describe otros animales en casa"
            ),
        ),
        migrations.AlterField(
            model_name="solicitudadopcion",
            name="patio",
            field=models.CharField(
                choices=[
                    ("si", "Sí, tengo patio"),
                    ("no", "No tengo patio"),
                    ("pequeño", "Tengo un patio pequeño"),
                    ("grande", "Tengo un patio grande"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="solicitudadopcion",
            name="perro",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="solicitudes",
                to="adopciones.perro",
            ),
        ),
        migrations.AlterField(
            model_name="solicitudadopcion",
            name="vivienda_tipo",
            field=models.CharField(
                choices=[
                    ("casa", "Casa"),
                    ("apartamento", "Apartamento"),
                    ("duplex", "Dúplex"),
                    ("parcela", "Parcela"),
                    ("otro", "Otro"),
                ],
                max_length=20,
            ),
        ),
    ]
